title: Muhammad Abdullah Abid
remote_theme: jekyll/minima
author:
  name: Muhammad Abdullah Abid
  email: hi@mabdullahabid.com
minima:
  date_format: "%Y-%m-%d"
  social_links:
    github: mabdullahabid
    linkedin: mabdullahabid
